const RETRO_WORLD_CUPS = Object.freeze({
  2006: Object.freeze({
    host: "Germany",
    teams: Object.freeze([
      { name: "Germany", group: "A", rating: 88 },
      { name: "Costa Rica", group: "A", rating: 74 },
      { name: "Poland", group: "A", rating: 77 },
      { name: "Ecuador", group: "A", rating: 78 },
      { name: "England", group: "B", rating: 88 },
      { name: "Paraguay", group: "B", rating: 80 },
      { name: "Trinidad and Tobago", group: "B", rating: 69 },
      { name: "Sweden", group: "B", rating: 83 },
      { name: "Argentina", group: "C", rating: 89 },
      { name: "Ivory Coast", group: "C", rating: 79 },
      { name: "Serbia and Montenegro", group: "C", rating: 78 },
      { name: "Netherlands", group: "C", rating: 87 },
      { name: "Mexico", group: "D", rating: 82 },
      { name: "Iran", group: "D", rating: 73 },
      { name: "Angola", group: "D", rating: 70 },
      { name: "Portugal", group: "D", rating: 88 },
      { name: "Italy", group: "E", rating: 88 },
      { name: "Ghana", group: "E", rating: 78 },
      { name: "USA", group: "E", rating: 77 },
      { name: "Czech Republic", group: "E", rating: 85 },
      { name: "Brazil", group: "F", rating: 92 },
      { name: "Croatia", group: "F", rating: 82 },
      { name: "Australia", group: "F", rating: 76 },
      { name: "Japan", group: "F", rating: 77 },
      { name: "France", group: "G", rating: 88 },
      { name: "Switzerland", group: "G", rating: 80 },
      { name: "South Korea", group: "G", rating: 78 },
      { name: "Togo", group: "G", rating: 69 },
      { name: "Spain", group: "H", rating: 87 },
      { name: "Ukraine", group: "H", rating: 82 },
      { name: "Tunisia", group: "H", rating: 73 },
      { name: "Saudi Arabia", group: "H", rating: 70 },
    ]),
  }),
  2010: Object.freeze({
    host: "South Africa",
    teams: Object.freeze([
      { name: "South Africa", group: "A", rating: 71 },
      { name: "Mexico", group: "A", rating: 78 },
      { name: "Uruguay", group: "A", rating: 83 },
      { name: "France", group: "A", rating: 82 },
      { name: "Argentina", group: "B", rating: 87 },
      { name: "Nigeria", group: "B", rating: 76 },
      { name: "South Korea", group: "B", rating: 75 },
      { name: "Greece", group: "B", rating: 77 },
      { name: "England", group: "C", rating: 83 },
      { name: "USA", group: "C", rating: 77 },
      { name: "Algeria", group: "C", rating: 72 },
      { name: "Slovenia", group: "C", rating: 73 },
      { name: "Germany", group: "D", rating: 87 },
      { name: "Australia", group: "D", rating: 74 },
      { name: "Serbia", group: "D", rating: 78 },
      { name: "Ghana", group: "D", rating: 80 },
      { name: "Netherlands", group: "E", rating: 87 },
      { name: "Denmark", group: "E", rating: 77 },
      { name: "Japan", group: "E", rating: 75 },
      { name: "Cameroon", group: "E", rating: 77 },
      { name: "Italy", group: "F", rating: 82 },
      { name: "Paraguay", group: "F", rating: 78 },
      { name: "New Zealand", group: "F", rating: 68 },
      { name: "Slovakia", group: "F", rating: 74 },
      { name: "Brazil", group: "G", rating: 88 },
      { name: "North Korea", group: "G", rating: 65 },
      { name: "Ivory Coast", group: "G", rating: 80 },
      { name: "Portugal", group: "G", rating: 84 },
      { name: "Spain", group: "H", rating: 90 },
      { name: "Switzerland", group: "H", rating: 76 },
      { name: "Honduras", group: "H", rating: 69 },
      { name: "Chile", group: "H", rating: 80 },
    ]),
  }),
  2014: Object.freeze({
    host: "Brazil",
    teams: Object.freeze([
      { name: "Brazil", group: "A", rating: 88 },
      { name: "Croatia", group: "A", rating: 81 },
      { name: "Mexico", group: "A", rating: 80 },
      { name: "Cameroon", group: "A", rating: 74 },
      { name: "Spain", group: "B", rating: 91 },
      { name: "Netherlands", group: "B", rating: 87 },
      { name: "Chile", group: "B", rating: 83 },
      { name: "Australia", group: "B", rating: 72 },
      { name: "Colombia", group: "C", rating: 85 },
      { name: "Greece", group: "C", rating: 77 },
      { name: "Ivory Coast", group: "C", rating: 78 },
      { name: "Japan", group: "C", rating: 76 },
      { name: "Uruguay", group: "D", rating: 86 },
      { name: "Costa Rica", group: "D", rating: 78 },
      { name: "England", group: "D", rating: 83 },
      { name: "Italy", group: "D", rating: 84 },
      { name: "Switzerland", group: "E", rating: 80 },
      { name: "Ecuador", group: "E", rating: 77 },
      { name: "France", group: "E", rating: 85 },
      { name: "Honduras", group: "E", rating: 69 },
      { name: "Argentina", group: "F", rating: 90 },
      { name: "Bosnia and Herzegovina", group: "F", rating: 78 },
      { name: "Iran", group: "F", rating: 71 },
      { name: "Nigeria", group: "F", rating: 76 },
      { name: "Germany", group: "G", rating: 92 },
      { name: "Portugal", group: "G", rating: 84 },
      { name: "Ghana", group: "G", rating: 78 },
      { name: "USA", group: "G", rating: 77 },
      { name: "Belgium", group: "H", rating: 84 },
      { name: "Algeria", group: "H", rating: 74 },
      { name: "Russia", group: "H", rating: 79 },
      { name: "South Korea", group: "H", rating: 72 },
    ]),
  }),
  2018: Object.freeze({
    host: "Russia",
    teams: Object.freeze([
      { name: "Russia", group: "A", rating: 81 },
      { name: "Saudi Arabia", group: "A", rating: 71 },
      { name: "Egypt", group: "A", rating: 74 },
      { name: "Uruguay", group: "A", rating: 86 },
      { name: "Portugal", group: "B", rating: 86 },
      { name: "Spain", group: "B", rating: 89 },
      { name: "Morocco", group: "B", rating: 75 },
      { name: "Iran", group: "B", rating: 73 },
      { name: "France", group: "C", rating: 92 },
      { name: "Australia", group: "C", rating: 75 },
      { name: "Peru", group: "C", rating: 78 },
      { name: "Denmark", group: "C", rating: 81 },
      { name: "Argentina", group: "D", rating: 87 },
      { name: "Iceland", group: "D", rating: 77 },
      { name: "Croatia", group: "D", rating: 87 },
      { name: "Nigeria", group: "D", rating: 77 },
      { name: "Brazil", group: "E", rating: 91 },
      { name: "Switzerland", group: "E", rating: 82 },
      { name: "Costa Rica", group: "E", rating: 76 },
      { name: "Serbia", group: "E", rating: 79 },
      { name: "Germany", group: "F", rating: 90 },
      { name: "Mexico", group: "F", rating: 82 },
      { name: "Sweden", group: "F", rating: 81 },
      { name: "South Korea", group: "F", rating: 76 },
      { name: "Belgium", group: "G", rating: 90 },
      { name: "Panama", group: "G", rating: 69 },
      { name: "Tunisia", group: "G", rating: 74 },
      { name: "England", group: "G", rating: 86 },
      { name: "Poland", group: "H", rating: 82 },
      { name: "Senegal", group: "H", rating: 79 },
      { name: "Colombia", group: "H", rating: 84 },
      { name: "Japan", group: "H", rating: 78 },
    ]),
  }),
  2022: Object.freeze({
    host: "Qatar",
    teams: Object.freeze([
      { name: "Qatar", group: "A", rating: 72 },
      { name: "Ecuador", group: "A", rating: 78 },
      { name: "Senegal", group: "A", rating: 82 },
      { name: "Netherlands", group: "A", rating: 87 },
      { name: "England", group: "B", rating: 89 },
      { name: "Iran", group: "B", rating: 77 },
      { name: "USA", group: "B", rating: 80 },
      { name: "Wales", group: "B", rating: 77 },
      { name: "Argentina", group: "C", rating: 92 },
      { name: "Saudi Arabia", group: "C", rating: 72 },
      { name: "Mexico", group: "C", rating: 80 },
      { name: "Poland", group: "C", rating: 81 },
      { name: "France", group: "D", rating: 92 },
      { name: "Australia", group: "D", rating: 76 },
      { name: "Denmark", group: "D", rating: 82 },
      { name: "Tunisia", group: "D", rating: 75 },
      { name: "Spain", group: "E", rating: 87 },
      { name: "Costa Rica", group: "E", rating: 76 },
      { name: "Germany", group: "E", rating: 87 },
      { name: "Japan", group: "E", rating: 80 },
      { name: "Belgium", group: "F", rating: 86 },
      { name: "Canada", group: "F", rating: 77 },
      { name: "Morocco", group: "F", rating: 83 },
      { name: "Croatia", group: "F", rating: 86 },
      { name: "Brazil", group: "G", rating: 91 },
      { name: "Serbia", group: "G", rating: 80 },
      { name: "Switzerland", group: "G", rating: 82 },
      { name: "Cameroon", group: "G", rating: 77 },
      { name: "Portugal", group: "H", rating: 88 },
      { name: "Ghana", group: "H", rating: 76 },
      { name: "Uruguay", group: "H", rating: 84 },
      { name: "South Korea", group: "H", rating: 79 },
    ]),
  }),
  2026: Object.freeze({
    host: "USA",
    teams: Object.freeze([
      { name: "Mexico", group: "A", rating: 79 },
      { name: "South Africa", group: "A", rating: 75 },
      { name: "Korea Republic", group: "A", rating: 80 },
      { name: "Czechia", group: "A", rating: 80 },
      { name: "Canada", group: "B", rating: 80 },
      { name: "Bosnia and Herzegovina", group: "B", rating: 76 },
      { name: "Qatar", group: "B", rating: 74 },
      { name: "Switzerland", group: "B", rating: 83 },
      { name: "Brazil", group: "C", rating: 88 },
      { name: "Morocco", group: "C", rating: 84 },
      { name: "Haiti", group: "C", rating: 69 },
      { name: "Scotland", group: "C", rating: 79 },
      { name: "USA", group: "D", rating: 82 },
      { name: "Paraguay", group: "D", rating: 79 },
      { name: "Australia", group: "D", rating: 79 },
      { name: "Türkiye", group: "D", rating: 83 },
      { name: "Germany", group: "E", rating: 86 },
      { name: "Curaçao", group: "E", rating: 71 },
      { name: "Côte d'Ivoire", group: "E", rating: 81 },
      { name: "Ecuador", group: "E", rating: 82 },
      { name: "Netherlands", group: "F", rating: 86 },
      { name: "Japan", group: "F", rating: 82 },
      { name: "Sweden", group: "F", rating: 80 },
      { name: "Tunisia", group: "F", rating: 75 },
      { name: "Belgium", group: "G", rating: 85 },
      { name: "Egypt", group: "G", rating: 80 },
      { name: "IR Iran", group: "G", rating: 78 },
      { name: "New Zealand", group: "G", rating: 71 },
      { name: "Spain", group: "H", rating: 91 },
      { name: "Cabo Verde", group: "H", rating: 74 },
      { name: "Saudi Arabia", group: "H", rating: 74 },
      { name: "Uruguay", group: "H", rating: 84 },
      { name: "France", group: "I", rating: 90 },
      { name: "Senegal", group: "I", rating: 82 },
      { name: "Iraq", group: "I", rating: 73 },
      { name: "Norway", group: "I", rating: 84 },
      { name: "Argentina", group: "J", rating: 90 },
      { name: "Algeria", group: "J", rating: 79 },
      { name: "Austria", group: "J", rating: 82 },
      { name: "Jordan", group: "J", rating: 73 },
      { name: "Portugal", group: "K", rating: 88 },
      { name: "Congo DR", group: "K", rating: 77 },
      { name: "Uzbekistan", group: "K", rating: 76 },
      { name: "Colombia", group: "K", rating: 84 },
      { name: "England", group: "L", rating: 88 },
      { name: "Croatia", group: "L", rating: 83 },
      { name: "Ghana", group: "L", rating: 77 },
      { name: "Panama", group: "L", rating: 74 },
    ]),
  }),
});
