const RETRO_WORLD_CUPS = Object.freeze({
  1998: Object.freeze({
    host: "France",
    rankingDate: "1998-05-20",
    rankingSource: "FIFA/Coca-Cola World Ranking, 20 May 1998",
    teams: Object.freeze([
      { name: "Brazil", group: "A", rating: 92, fifaRank: 1, fifaPoints: 72 },
      { name: "Scotland", group: "A", rating: 76, fifaRank: 41, fifaPoints: 48 },
      { name: "Morocco", group: "A", rating: 77, fifaRank: 13, fifaPoints: 57 },
      { name: "Norway", group: "A", rating: 81, fifaRank: 7, fifaPoints: 60 },
      { name: "Italy", group: "B", rating: 89, fifaRank: 14, fifaPoints: 57 },
      { name: "Chile", group: "B", rating: 79, fifaRank: 9, fifaPoints: 59 },
      { name: "Cameroon", group: "B", rating: 76, fifaRank: 49, fifaPoints: 45 },
      { name: "Austria", group: "B", rating: 76, fifaRank: 31, fifaPoints: 52 },
      { name: "France", group: "C", rating: 88, fifaRank: 18, fifaPoints: 56 },
      { name: "South Africa", group: "C", rating: 73, fifaRank: 24, fifaPoints: 55 },
      { name: "Saudi Arabia", group: "C", rating: 70, fifaRank: 34, fifaPoints: 51 },
      { name: "Denmark", group: "C", rating: 80, fifaRank: 27, fifaPoints: 53 },
      { name: "Spain", group: "D", rating: 86, fifaRank: 15, fifaPoints: 56 },
      { name: "Bulgaria", group: "D", rating: 75, fifaRank: 35, fifaPoints: 50 },
      { name: "Nigeria", group: "D", rating: 80, fifaRank: 74, fifaPoints: 37 },
      { name: "Paraguay", group: "D", rating: 78, fifaRank: 29, fifaPoints: 52 },
      { name: "Netherlands", group: "E", rating: 88, fifaRank: 25, fifaPoints: 54 },
      { name: "Belgium", group: "E", rating: 77, fifaRank: 36, fifaPoints: 50 },
      { name: "South Korea", group: "E", rating: 71, fifaRank: 20, fifaPoints: 55 },
      { name: "Mexico", group: "E", rating: 79, fifaRank: 4, fifaPoints: 61 },
      { name: "Germany", group: "F", rating: 85, fifaRank: 2, fifaPoints: 65 },
      { name: "USA", group: "F", rating: 73, fifaRank: 11, fifaPoints: 58 },
      { name: "Yugoslavia", group: "F", rating: 81, fifaRank: 8, fifaPoints: 59 },
      { name: "Iran", group: "F", rating: 72, fifaRank: 42, fifaPoints: 48 },
      { name: "Romania", group: "G", rating: 82, fifaRank: 22, fifaPoints: 55 },
      { name: "Colombia", group: "G", rating: 79, fifaRank: 10, fifaPoints: 58 },
      { name: "England", group: "G", rating: 85, fifaRank: 5, fifaPoints: 60 },
      { name: "Tunisia", group: "G", rating: 71, fifaRank: 21, fifaPoints: 55 },
      { name: "Argentina", group: "H", rating: 88, fifaRank: 6, fifaPoints: 60 },
      { name: "Japan", group: "H", rating: 70, fifaRank: 12, fifaPoints: 58 },
      { name: "Jamaica", group: "H", rating: 67, fifaRank: 30, fifaPoints: 52 },
      { name: "Croatia", group: "H", rating: 82, fifaRank: 19, fifaPoints: 56 },
    ]),
  }),
  2002: Object.freeze({
    host: "Korea/Japan",
    rankingDate: "2002-05-15",
    rankingSource: "FIFA/Coca-Cola World Ranking, 15 May 2002",
    teams: Object.freeze([
      { name: "France", group: "A", rating: 90, fifaRank: 1, fifaPoints: 802 },
      { name: "Senegal", group: "A", rating: 77, fifaRank: 42, fifaPoints: 599 },
      { name: "Uruguay", group: "A", rating: 76, fifaRank: 24, fifaPoints: 652 },
      { name: "Denmark", group: "A", rating: 81, fifaRank: 20, fifaPoints: 657 },
      { name: "Spain", group: "B", rating: 86, fifaRank: 8, fifaPoints: 713 },
      { name: "Slovenia", group: "B", rating: 72, fifaRank: 25, fifaPoints: 649 },
      { name: "Paraguay", group: "B", rating: 78, fifaRank: 18, fifaPoints: 671 },
      { name: "South Africa", group: "B", rating: 72, fifaRank: 37, fifaPoints: 623 },
      { name: "Brazil", group: "C", rating: 91, fifaRank: 2, fifaPoints: 784 },
      { name: "Turkey", group: "C", rating: 81, fifaRank: 22, fifaPoints: 654 },
      { name: "China", group: "C", rating: 67, fifaRank: 50, fifaPoints: 566 },
      { name: "Costa Rica", group: "C", rating: 73, fifaRank: 29, fifaPoints: 643 },
      { name: "South Korea", group: "D", rating: 78, fifaRank: 40, fifaPoints: 603 },
      { name: "Poland", group: "D", rating: 74, fifaRank: 38, fifaPoints: 615 },
      { name: "United States", group: "D", rating: 80, fifaRank: 13, fifaPoints: 690 },
      { name: "Portugal", group: "D", rating: 87, fifaRank: 5, fifaPoints: 726 },
      { name: "Germany", group: "E", rating: 84, fifaRank: 11, fifaPoints: 695 },
      { name: "Saudi Arabia", group: "E", rating: 67, fifaRank: 34, fifaPoints: 627 },
      { name: "Republic of Ireland", group: "E", rating: 79, fifaRank: 15, fifaPoints: 674 },
      { name: "Cameroon", group: "E", rating: 75, fifaRank: 17, fifaPoints: 672 },
      { name: "Argentina", group: "F", rating: 89, fifaRank: 2, fifaPoints: 784 },
      { name: "Nigeria", group: "F", rating: 77, fifaRank: 27, fifaPoints: 644 },
      { name: "England", group: "F", rating: 85, fifaRank: 12, fifaPoints: 694 },
      { name: "Sweden", group: "F", rating: 81, fifaRank: 19, fifaPoints: 665 },
      { name: "Italy", group: "G", rating: 87, fifaRank: 6, fifaPoints: 717 },
      { name: "Ecuador", group: "G", rating: 74, fifaRank: 35, fifaPoints: 624 },
      { name: "Croatia", group: "G", rating: 78, fifaRank: 21, fifaPoints: 655 },
      { name: "Mexico", group: "G", rating: 82, fifaRank: 7, fifaPoints: 716 },
      { name: "Japan", group: "H", rating: 76, fifaRank: 32, fifaPoints: 634 },
      { name: "Belgium", group: "H", rating: 77, fifaRank: 23, fifaPoints: 653 },
      { name: "Russia", group: "H", rating: 75, fifaRank: 27, fifaPoints: 644 },
      { name: "Tunisia", group: "H", rating: 70, fifaRank: 30, fifaPoints: 635 },
    ]),
  }),
  2006: Object.freeze({
    host: "Germany",
    teams: Object.freeze([
      { name: "Germany", group: "A", rating: 89 },
      { name: "Costa Rica", group: "A", rating: 73 },
      { name: "Poland", group: "A", rating: 77 },
      { name: "Ecuador", group: "A", rating: 79 },
      { name: "England", group: "B", rating: 87 },
      { name: "Paraguay", group: "B", rating: 79 },
      { name: "Trinidad and Tobago", group: "B", rating: 68 },
      { name: "Sweden", group: "B", rating: 82 },
      { name: "Argentina", group: "C", rating: 89 },
      { name: "Ivory Coast", group: "C", rating: 80 },
      { name: "Serbia and Montenegro", group: "C", rating: 76 },
      { name: "Netherlands", group: "C", rating: 86 },
      { name: "Mexico", group: "D", rating: 82 },
      { name: "Iran", group: "D", rating: 73 },
      { name: "Angola", group: "D", rating: 70 },
      { name: "Portugal", group: "D", rating: 88 },
      { name: "Italy", group: "E", rating: 91 },
      { name: "Ghana", group: "E", rating: 79 },
      { name: "USA", group: "E", rating: 76 },
      { name: "Czech Republic", group: "E", rating: 84 },
      { name: "Brazil", group: "F", rating: 89 },
      { name: "Croatia", group: "F", rating: 81 },
      { name: "Australia", group: "F", rating: 78 },
      { name: "Japan", group: "F", rating: 76 },
      { name: "France", group: "G", rating: 90 },
      { name: "Switzerland", group: "G", rating: 81 },
      { name: "South Korea", group: "G", rating: 77 },
      { name: "Togo", group: "G", rating: 69 },
      { name: "Spain", group: "H", rating: 86 },
      { name: "Ukraine", group: "H", rating: 81 },
      { name: "Tunisia", group: "H", rating: 73 },
      { name: "Saudi Arabia", group: "H", rating: 70 },
    ]),
  }),
  2010: Object.freeze({
    host: "South Africa",
    teams: Object.freeze([
      { name: "South Africa", group: "A", rating: 71 },
      { name: "Mexico", group: "A", rating: 78 },
      { name: "Uruguay", group: "A", rating: 83 },
      { name: "France", group: "A", rating: 82 },
      { name: "Argentina", group: "B", rating: 87 },
      { name: "Nigeria", group: "B", rating: 76 },
      { name: "South Korea", group: "B", rating: 75 },
      { name: "Greece", group: "B", rating: 77 },
      { name: "England", group: "C", rating: 83 },
      { name: "USA", group: "C", rating: 77 },
      { name: "Algeria", group: "C", rating: 72 },
      { name: "Slovenia", group: "C", rating: 73 },
      { name: "Germany", group: "D", rating: 87 },
      { name: "Australia", group: "D", rating: 74 },
      { name: "Serbia", group: "D", rating: 78 },
      { name: "Ghana", group: "D", rating: 80 },
      { name: "Netherlands", group: "E", rating: 87 },
      { name: "Denmark", group: "E", rating: 77 },
      { name: "Japan", group: "E", rating: 75 },
      { name: "Cameroon", group: "E", rating: 77 },
      { name: "Italy", group: "F", rating: 82 },
      { name: "Paraguay", group: "F", rating: 78 },
      { name: "New Zealand", group: "F", rating: 68 },
      { name: "Slovakia", group: "F", rating: 74 },
      { name: "Brazil", group: "G", rating: 88 },
      { name: "North Korea", group: "G", rating: 65 },
      { name: "Ivory Coast", group: "G", rating: 80 },
      { name: "Portugal", group: "G", rating: 84 },
      { name: "Spain", group: "H", rating: 90 },
      { name: "Switzerland", group: "H", rating: 76 },
      { name: "Honduras", group: "H", rating: 69 },
      { name: "Chile", group: "H", rating: 80 },
    ]),
  }),
  2014: Object.freeze({
    host: "Brazil",
    teams: Object.freeze([
      { name: "Brazil", group: "A", rating: 88 },
      { name: "Croatia", group: "A", rating: 81 },
      { name: "Mexico", group: "A", rating: 80 },
      { name: "Cameroon", group: "A", rating: 74 },
      { name: "Spain", group: "B", rating: 91 },
      { name: "Netherlands", group: "B", rating: 87 },
      { name: "Chile", group: "B", rating: 83 },
      { name: "Australia", group: "B", rating: 72 },
      { name: "Colombia", group: "C", rating: 85 },
      { name: "Greece", group: "C", rating: 77 },
      { name: "Ivory Coast", group: "C", rating: 78 },
      { name: "Japan", group: "C", rating: 76 },
      { name: "Uruguay", group: "D", rating: 86 },
      { name: "Costa Rica", group: "D", rating: 78 },
      { name: "England", group: "D", rating: 83 },
      { name: "Italy", group: "D", rating: 84 },
      { name: "Switzerland", group: "E", rating: 80 },
      { name: "Ecuador", group: "E", rating: 77 },
      { name: "France", group: "E", rating: 85 },
      { name: "Honduras", group: "E", rating: 69 },
      { name: "Argentina", group: "F", rating: 90 },
      { name: "Bosnia and Herzegovina", group: "F", rating: 78 },
      { name: "Iran", group: "F", rating: 71 },
      { name: "Nigeria", group: "F", rating: 76 },
      { name: "Germany", group: "G", rating: 92 },
      { name: "Portugal", group: "G", rating: 84 },
      { name: "Ghana", group: "G", rating: 78 },
      { name: "USA", group: "G", rating: 77 },
      { name: "Belgium", group: "H", rating: 84 },
      { name: "Algeria", group: "H", rating: 74 },
      { name: "Russia", group: "H", rating: 79 },
      { name: "South Korea", group: "H", rating: 72 },
    ]),
  }),
  2016: Object.freeze({
    host: "France",
    competition: "UEFA Euro",
    teams: Object.freeze([
      { name: "France", group: "A", rating: 88 },
      { name: "Romania", group: "A", rating: 75 },
      { name: "Albania", group: "A", rating: 72 },
      { name: "Switzerland", group: "A", rating: 81 },
      { name: "England", group: "B", rating: 85 },
      { name: "Russia", group: "B", rating: 79 },
      { name: "Wales", group: "B", rating: 82 },
      { name: "Slovakia", group: "B", rating: 79 },
      { name: "Germany", group: "C", rating: 89 },
      { name: "Ukraine", group: "C", rating: 78 },
      { name: "Poland", group: "C", rating: 83 },
      { name: "Northern Ireland", group: "C", rating: 75 },
      { name: "Spain", group: "D", rating: 88 },
      { name: "Czech Republic", group: "D", rating: 78 },
      { name: "Turkey", group: "D", rating: 80 },
      { name: "Croatia", group: "D", rating: 86 },
      { name: "Belgium", group: "E", rating: 87 },
      { name: "Italy", group: "E", rating: 86 },
      { name: "Republic of Ireland", group: "E", rating: 77 },
      { name: "Sweden", group: "E", rating: 80 },
      { name: "Portugal", group: "F", rating: 87 },
      { name: "Iceland", group: "F", rating: 78 },
      { name: "Austria", group: "F", rating: 81 },
      { name: "Hungary", group: "F", rating: 77 },
    ]),
  }),
  2020: Object.freeze({
    host: "Europe",
    competition: "UEFA Euro",
    ratingMethod: "Blended retrospective strength: FIFA 21 national-team/player quality, 2020/21 Nations League and club form, and Euro 2020 tournament performance.",
    teams: Object.freeze([
      { name: "Turkey", group: "A", rating: 78 },
      { name: "Italy", group: "A", rating: 91 },
      { name: "Wales", group: "A", rating: 81 },
      { name: "Switzerland", group: "A", rating: 85 },
      { name: "Denmark", group: "B", rating: 88 },
      { name: "Finland", group: "B", rating: 75 },
      { name: "Belgium", group: "B", rating: 89 },
      { name: "Russia", group: "B", rating: 78 },
      { name: "Netherlands", group: "C", rating: 86 },
      { name: "Ukraine", group: "C", rating: 84 },
      { name: "Austria", group: "C", rating: 82 },
      { name: "North Macedonia", group: "C", rating: 73 },
      { name: "England", group: "D", rating: 90 },
      { name: "Croatia", group: "D", rating: 84 },
      { name: "Scotland", group: "D", rating: 77 },
      { name: "Czech Republic", group: "D", rating: 84 },
      { name: "Spain", group: "E", rating: 89 },
      { name: "Sweden", group: "E", rating: 82 },
      { name: "Poland", group: "E", rating: 81 },
      { name: "Slovakia", group: "E", rating: 77 },
      { name: "Hungary", group: "F", rating: 80 },
      { name: "Portugal", group: "F", rating: 88 },
      { name: "France", group: "F", rating: 89 },
      { name: "Germany", group: "F", rating: 86 },
    ]),
  }),
  2018: Object.freeze({
    host: "Russia",
    teams: Object.freeze([
      { name: "Russia", group: "A", rating: 81 },
      { name: "Saudi Arabia", group: "A", rating: 71 },
      { name: "Egypt", group: "A", rating: 74 },
      { name: "Uruguay", group: "A", rating: 86 },
      { name: "Portugal", group: "B", rating: 86 },
      { name: "Spain", group: "B", rating: 89 },
      { name: "Morocco", group: "B", rating: 75 },
      { name: "Iran", group: "B", rating: 73 },
      { name: "France", group: "C", rating: 92 },
      { name: "Australia", group: "C", rating: 75 },
      { name: "Peru", group: "C", rating: 78 },
      { name: "Denmark", group: "C", rating: 81 },
      { name: "Argentina", group: "D", rating: 87 },
      { name: "Iceland", group: "D", rating: 77 },
      { name: "Croatia", group: "D", rating: 87 },
      { name: "Nigeria", group: "D", rating: 77 },
      { name: "Brazil", group: "E", rating: 91 },
      { name: "Switzerland", group: "E", rating: 82 },
      { name: "Costa Rica", group: "E", rating: 76 },
      { name: "Serbia", group: "E", rating: 79 },
      { name: "Germany", group: "F", rating: 90 },
      { name: "Mexico", group: "F", rating: 82 },
      { name: "Sweden", group: "F", rating: 81 },
      { name: "South Korea", group: "F", rating: 76 },
      { name: "Belgium", group: "G", rating: 90 },
      { name: "Panama", group: "G", rating: 69 },
      { name: "Tunisia", group: "G", rating: 74 },
      { name: "England", group: "G", rating: 86 },
      { name: "Poland", group: "H", rating: 82 },
      { name: "Senegal", group: "H", rating: 79 },
      { name: "Colombia", group: "H", rating: 84 },
      { name: "Japan", group: "H", rating: 78 },
    ]),
  }),
  2022: Object.freeze({
    host: "Qatar",
    teams: Object.freeze([
      { name: "Qatar", group: "A", rating: 72 },
      { name: "Ecuador", group: "A", rating: 78 },
      { name: "Senegal", group: "A", rating: 82 },
      { name: "Netherlands", group: "A", rating: 87 },
      { name: "England", group: "B", rating: 89 },
      { name: "Iran", group: "B", rating: 77 },
      { name: "USA", group: "B", rating: 80 },
      { name: "Wales", group: "B", rating: 77 },
      { name: "Argentina", group: "C", rating: 92 },
      { name: "Saudi Arabia", group: "C", rating: 72 },
      { name: "Mexico", group: "C", rating: 80 },
      { name: "Poland", group: "C", rating: 81 },
      { name: "France", group: "D", rating: 92 },
      { name: "Australia", group: "D", rating: 76 },
      { name: "Denmark", group: "D", rating: 82 },
      { name: "Tunisia", group: "D", rating: 75 },
      { name: "Spain", group: "E", rating: 87 },
      { name: "Costa Rica", group: "E", rating: 76 },
      { name: "Germany", group: "E", rating: 87 },
      { name: "Japan", group: "E", rating: 80 },
      { name: "Belgium", group: "F", rating: 86 },
      { name: "Canada", group: "F", rating: 77 },
      { name: "Morocco", group: "F", rating: 83 },
      { name: "Croatia", group: "F", rating: 86 },
      { name: "Brazil", group: "G", rating: 91 },
      { name: "Serbia", group: "G", rating: 80 },
      { name: "Switzerland", group: "G", rating: 82 },
      { name: "Cameroon", group: "G", rating: 77 },
      { name: "Portugal", group: "H", rating: 88 },
      { name: "Ghana", group: "H", rating: 76 },
      { name: "Uruguay", group: "H", rating: 84 },
      { name: "South Korea", group: "H", rating: 79 },
    ]),
  }),
  2024: Object.freeze({
    host: "United States",
    competition: "CONMEBOL Copa América",
    rankingDate: "2024-06-20",
    rankingSource: "FIFA/Coca-Cola World Ranking, June 2024; used as one calibration input",
    ratingMethodology: "Custom simulator ratings combine 2023/24 club performance, international form entering June 2024, contemporary public EA/FIFA rating references, June 2024 FIFA ranking, squad quality and tactical strength. Copa América results are a secondary calibration signal, not the primary input.",
    teams: Object.freeze([
      { name: "Argentina", group: "A", rating: 90, fifaRank: 1 },
      { name: "Peru", group: "A", rating: 74, fifaRank: 32 },
      { name: "Chile", group: "A", rating: 76, fifaRank: 42 },
      { name: "Canada", group: "A", rating: 78, fifaRank: 49 },
      { name: "Mexico", group: "B", rating: 78, fifaRank: 15 },
      { name: "Ecuador", group: "B", rating: 81, fifaRank: 30 },
      { name: "Venezuela", group: "B", rating: 80, fifaRank: 54 },
      { name: "Jamaica", group: "B", rating: 70, fifaRank: 53 },
      { name: "United States", group: "C", rating: 79, fifaRank: 11 },
      { name: "Uruguay", group: "C", rating: 89, fifaRank: 14 },
      { name: "Panama", group: "C", rating: 74, fifaRank: 43 },
      { name: "Bolivia", group: "C", rating: 66, fifaRank: 84 },
      { name: "Brazil", group: "D", rating: 86, fifaRank: 4 },
      { name: "Colombia", group: "D", rating: 88, fifaRank: 12 },
      { name: "Paraguay", group: "D", rating: 72, fifaRank: 58 },
      { name: "Costa Rica", group: "D", rating: 71, fifaRank: 52 },
    ]),
  }),
  2026: Object.freeze({
    host: "USA",
    teams: Object.freeze([
      { name: "Mexico", group: "A", rating: 79 },
      { name: "South Africa", group: "A", rating: 75 },
      { name: "Korea Republic", group: "A", rating: 80 },
      { name: "Czechia", group: "A", rating: 80 },
      { name: "Canada", group: "B", rating: 80 },
      { name: "Bosnia and Herzegovina", group: "B", rating: 76 },
      { name: "Qatar", group: "B", rating: 74 },
      { name: "Switzerland", group: "B", rating: 83 },
      { name: "Brazil", group: "C", rating: 88 },
      { name: "Morocco", group: "C", rating: 84 },
      { name: "Haiti", group: "C", rating: 69 },
      { name: "Scotland", group: "C", rating: 79 },
      { name: "USA", group: "D", rating: 82 },
      { name: "Paraguay", group: "D", rating: 79 },
      { name: "Australia", group: "D", rating: 79 },
      { name: "Türkiye", group: "D", rating: 83 },
      { name: "Germany", group: "E", rating: 86 },
      { name: "Curaçao", group: "E", rating: 71 },
      { name: "Côte d'Ivoire", group: "E", rating: 81 },
      { name: "Ecuador", group: "E", rating: 82 },
      { name: "Netherlands", group: "F", rating: 86 },
      { name: "Japan", group: "F", rating: 82 },
      { name: "Sweden", group: "F", rating: 80 },
      { name: "Tunisia", group: "F", rating: 75 },
      { name: "Belgium", group: "G", rating: 85 },
      { name: "Egypt", group: "G", rating: 80 },
      { name: "IR Iran", group: "G", rating: 78 },
      { name: "New Zealand", group: "G", rating: 71 },
      { name: "Spain", group: "H", rating: 91 },
      { name: "Cabo Verde", group: "H", rating: 74 },
      { name: "Saudi Arabia", group: "H", rating: 74 },
      { name: "Uruguay", group: "H", rating: 84 },
      { name: "France", group: "I", rating: 90 },
      { name: "Senegal", group: "I", rating: 82 },
      { name: "Iraq", group: "I", rating: 73 },
      { name: "Norway", group: "I", rating: 84 },
      { name: "Argentina", group: "J", rating: 90 },
      { name: "Algeria", group: "J", rating: 79 },
      { name: "Austria", group: "J", rating: 82 },
      { name: "Jordan", group: "J", rating: 73 },
      { name: "Portugal", group: "K", rating: 88 },
      { name: "Congo DR", group: "K", rating: 77 },
      { name: "Uzbekistan", group: "K", rating: 76 },
      { name: "Colombia", group: "K", rating: 84 },
      { name: "England", group: "L", rating: 88 },
      { name: "Croatia", group: "L", rating: 83 },
      { name: "Ghana", group: "L", rating: 77 },
      { name: "Panama", group: "L", rating: 74 },
    ]),
  }),
});
